# Generated by Django 3.2.9 on 2022-06-29 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='detail',
        ),
    ]
