# Generated by Django 3.2.9 on 2022-06-30 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_items_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detail',
        ),
    ]
