# Generated by Django 3.2.9 on 2022-07-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_item_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_link',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
