# Generated by Django 3.2.9 on 2022-07-02 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_item_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_link',
        ),
    ]
